//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPlanningAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime Date { get; set; }
        public bool Done { get; set; }
        public int ChecklistId { get; set; }
    
        public virtual Checklist Checklist { get; set; }
    }
}
