//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPlanningAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionType()
        {
            this.WPlannerCompany = new HashSet<WPlannerCompany>();
        }
    
        public int SubscriptionTypeId { get; set; }
        public int Months { get; set; }
        public int QuantityWPlanners { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public double Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WPlannerCompany> WPlannerCompany { get; set; }
    }
}
