//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPlanningAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wedding
    {
        public int WeddingId { get; set; }
        public int FianceeId { get; set; }
        public System.DateTime Date { get; set; }
        public double InitialBudget { get; set; }
        public int BudgetId { get; set; }
        public string Location { get; set; }
        public int QuantityInvitations { get; set; }
        public int ChecklistId { get; set; }
        public int CatalogueId { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual Catalogue Catalogue { get; set; }
        public virtual Checklist Checklist { get; set; }
        public virtual Couple Couple { get; set; }
    }
}
