//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPlanningAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WPlannerCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WPlannerCompany()
        {
            this.WPlanner = new HashSet<WPlanner>();
        }
    
        public int WPlannerCompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public int SubscriptionTypeId { get; set; }
        public string Email { get; set; }
    
        public virtual SubscriptionType SubscriptionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WPlanner> WPlanner { get; set; }
    }
}
