//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPlanningAPI.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int OptionId { get; set; }
        public string Description { get; set; }
        public bool Chosen { get; set; }
        public int SubCatalogueId { get; set; }
    
        public virtual SubCatalogue SubCatalogue { get; set; }
    }
}
