//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPlanningAPI.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WPlanningDBEntities : DbContext
    {
        public WPlanningDBEntities()
            : base("name=WPlanningDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Budget> Budget { get; set; }
        public virtual DbSet<Catalogue> Catalogue { get; set; }
        public virtual DbSet<Checklist> Checklist { get; set; }
        public virtual DbSet<Couple> Couple { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<Option> Option { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<SubCatalogue> SubCatalogue { get; set; }
        public virtual DbSet<SubscriptionType> SubscriptionType { get; set; }
        public virtual DbSet<Wedding> Wedding { get; set; }
        public virtual DbSet<WPlanner> WPlanner { get; set; }
        public virtual DbSet<WPlannerCompany> WPlannerCompany { get; set; }
    }
}
