//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPlanningAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WPlanner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WPlanner()
        {
            this.Couple = new HashSet<Couple>();
        }
    
        public int WPlannerId { get; set; }
        public int WPlannerCompanyId { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Password { get; set; }
        public string Usr { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Couple> Couple { get; set; }
        public virtual Person Person { get; set; }
        public virtual WPlannerCompany WPlannerCompany { get; set; }
    }
}
